### ISSUE TITLE
File("somePath") .glob("**/*.{ext}") results in empty list

### ISSUE THREAD

**Issue by gaydenko** [pathikrit/better-files#57] opened 2015-12-18 11:09 UTC
Hi! In 2.14 `File("somePath") .glob("**/*.{ext}")` results in empty list, while with 2.13 is OK. Has some semantic changed form 2.13?

BTW, the spec checks globbing with `"a" / "b"` only, skipping `File("c")` case.

**Comment by pathikrit** [comment] 2016-01-30 22:19
Hi @gaydenko - I could not reproduce this. Feel free to reopen this if you have a reproducible test case. Thanks!

**Comment by gaydenko** [comment] 2016-01-31 00:01
@pathikrit ,

At the moment the problem is I can not find how to **not**-reproduce the issue :) Having this code

```scala
import better.files._

object TestBestFiles {

  def main(args: Array[String]): Unit = {
    val path = "/wrk/z/files"
    val ext = "bc"
    val dir = File(path)
    val files1: Seq[File] = dir.glob(s"**/*.{$ext}").toList
    println(files1.size)
    val files2 = dir.listRecursively.filter(_.extension == Some(s".$ext"))
    println(files2.size)
  }
}
```
with
```txt
⋊> ~ ls /wrk/z/files/
a.bc  d.ef
```
I get
```txt
0
1
```
output. By the way, README probably must be corrected in globbing chapter: 
```scala
val matches: Seq[File] = dir.glob("**/*.{java,scala}")
```
But `glob` returns `Iterator`.

**Comment by pathikrit** [comment] 2016-01-31 00:10
Your problem is you are doing `dir.glob(s"**/*.{$ext}")`. You should do `dir.glob(s"**/*.${ext}")` instead. 
The first one looks for files which has extension `.{ef}` instead of `.ef`.

I will fix the doc about iterator

**Comment by gaydenko** [comment] 2016-01-31 00:16
`{ }` here are part of glob expression as, say, `"**/*.{java,scala}"` - just the list with single element. And setting directly to `"**/*.bc"` doesn't help at any case. With 2.13.0 any variant does work.

**Comment by gaydenko** [comment] 2016-01-31 01:00
@pathikrit , I have found commit resulted in the issue, it is https://github.com/pathikrit/better-files/commit/58ea353b14586448255c0fdfc0011de22c176606 

This code with old `glob` definition (`glob3` here)
```scala
import better.files._

object TestBestFiles {

  def main(args: Array[String]): Unit = {
    val path = "/wrk/z/files"
    val ext = "bc"
    val dir = File(path)
    val files1 = dir.glob(s"**/*.{$ext}")
    println(files1.size) // 0
    val files2 = dir.listRecursively.filter(_.extension == Some(s".$ext"))
    println(files2.size) // 1

    def glob3(file: File, pattern: String, syntax: String = "glob", ignoreIOExceptions: Boolean = false) = {
      val matcher = file.fileSystem.getPathMatcher(s"$syntax:$pattern")
      java.nio.file.Files.walk(file.path).filter(new java.util.function.Predicate[java.nio.file.Path] {
        override def test(path: java.nio.file.Path) = matcher.matches(path)
      })
    }

    val files3 = glob3(dir, s"**/*.{$ext}").toArray.toSeq
    println(files3.size) // 1
  }
}
```
results in 
```txt
0
1
1
```

**Comment by pathikrit** [comment] 2016-01-31 03:39
@gaydenko : Thanks for the code. This is really puzzling - I cannot reproduce it!
I added tests here: https://github.com/pathikrit/better-files/commit/a6ee222470bebe3780317fdf4f22c6222475706c and they work as expected!

**Comment by gaydenko** [comment] 2016-01-31 07:36
@pathikrit , let's find difference :)

1. Have you tried to run above code directly, out of specs? I mean `dir` is defined by the single String literal, and the path is **absolute** path.

2. OS? Java? Scala? Mine ones:
```txt
~ $ uname -a
Linux jazz 4.3.3-3-ARCH #1 SMP PREEMPT Wed Jan 20 08:12:23 CET 2016 x86_64 GNU/Linux
~ $ java -version
java version "1.8.0_72"
Java(TM) SE Runtime Environment (build 1.8.0_72-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.72-b15, mixed mode)
~ $ scala -version
Scala code runner version 2.11.7 -- Copyright 2002-2013, LAMP/EPFL
```

3. Has specs environment some implicits?

**Comment by pathikrit** [comment] 2016-01-31 07:59
1. I do use the absolute path in line 119: https://github.com/pathikrit/better-files/commit/a6ee222470bebe3780317fdf4f22c6222475706c#diff-3c136f71bba4f951c2bd8d8e781346d6R119

2. I am on OSX and tests pass locally. I also have continuous integration on circleci which passed on Ubuntu: https://circleci.com/gh/pathikrit/better-files/492

```
> uname -a
Darwin osxmb-4.local 14.5.0 Darwin Kernel Version 14.5.0: Tue Sep  1 21:23:09 PDT 2015; root:xnu-2782.50.1~1/RELEASE_X86_64 x86_64

> java -version
java version "1.8.0_20"
Java(TM) SE Runtime Environment (build 1.8.0_20-b26)
Java HotSpot(TM) 64-Bit Server VM (build 25.20-b23, mixed mode)

> scala -version    
Scala code runner version 2.11.7 -- Copyright 2002-2013, LAMP/EPFL
```

Although I have Scala 2.11, the tests run against both Scala 2.10 and 2.11 and both passes. Basically, the only system I don't have tests against is Windows...

This is very interesting! Let me try to copy your code and run it stand-alone separate from tests.

**Comment by pathikrit** [comment] 2016-01-31 08:26
Managed to repro finally! Will add test case and fix and cut a new release.

**Comment by gaydenko** [comment] 2016-01-31 08:32
@pathikrit , I have run `test` task and got two failed tests:
```txt
...
[info] - should glob *** FAILED ***
[info]   Stream("t2.txt", "t1.txt") did not equal List("t1.txt", "t2.txt") (FileSpec.scala:117)
[info] - should support names/extensions !!! CANCELED !!!
[info]   FileSpec.this.isCI was false (FileSpec.scala:132)
[info] - should hide/unhide
[info] - should support parent/child
[info] - should support siblings
[info] - should support sorting *** FAILED ***
[info]   /tmp/better-files1972228565861938148/b was empty (FileSpec.scala:173)
...
```

**Comment by gaydenko** [comment] 2016-01-31 08:33
> Managed to repro finally! 
Great!

**Comment by pathikrit** [comment] 2016-01-31 08:43
Checked in fix. Will release next version when tests pass. Thanks!

**Closed by pathikrit** 2016-01-31 08:43 UTC
Labels: bug
