### ISSUE TITLE
[Feature Request] A child traversal that doesn't leak the resource created by newDirectoryStream

### ISSUE THREAD

**Issue by gblahaerath** [pathikrit/better-files#291] opened 2019-02-03 22:12 UTC
While doing some deep recursive file scanning I discovered that the calls like File.children do not manage the DirectoryStream resource causing file handles to be eaten up.  The underlying Java call, Files.list() returns a Stream[Path] that also has a "close" method on it. It will, of course, auto close on GC, but that's not ideal.  

My own solution was to write a method to that outputs an Dispose[Iterator[File]].  I'd be happy to add that method to this library, just let me know what name suits you. This would let someone do something like:

```
   val files = File(path).disposableList().map(_.toList).get
```

Another possibility is to output a Stream[File] that materializes the contents, and when the end of the contents is reached, a close is called.  Not as great, though its a handy approach for a sloppy coding a utility.

I think an approach in the future for scala 3 would be to add a trait with an arg to the existing iterators that does the dispose.  Existing code would continue to work, and anyone looking to dispose the resource could get to it with explicit casting or some reflect duck typing.

**Comment by pathikrit** [comment] 2019-02-24 04:17
Duplicate of #283

**Closed by pathikrit** 2019-02-24 04:17 UTC
Labels: bug
