### ISSUE TITLE
loadBytes on Resource

### ISSUE THREAD

**Issue by JakubKahovec** [pathikrit/better-files#42] opened 2015-11-01 20:18 UTC
Hi,

First thank you for your library it makes life working with files much easier :-)
So what would be the recommended way (without converting char to byte) to get bytes from a resource (fetched through resource"/myresource.json") as loadBytes only exist on File class

Thanks

Jakub

**Comment by pathikrit** [comment] 2015-11-02 02:44
Hi, yes, the Resource APIs are not done yet. Future versions of better-files would have resource APIs similar to the files. 

For now, I this would work using `better-files`:

```scala
val bytes: Iterator[Byte] = this.getClass.getResourceAsStream("myresource.json").bytes
```

Duplicate of #9

**Comment by pathikrit** [comment] 2015-11-02 02:44
See: https://github.com/pathikrit/better-files/blob/51fefec215e7016d69f110938563d18b64a1880b/core/src/main/scala/better/files/Implicits.scala#L62

**Closed by pathikrit** 2015-11-02 02:44 UTC

**Comment by JakubKahovec** [comment] 2015-11-02 08:00
Works fine, thank you.

**Comment by pathikrit** [comment] 2015-11-02 08:06
Forgot to mention, you might want `.buffered.bytes` for large files..
