### ISSUE TITLE
Difference semantic between unix commands and unix dsl

### ISSUE THREAD

**Issue by Troxid** [pathikrit/better-files#218] opened 2018-02-06 13:55 UTC
Unix dsl methods don't work as expected.
Example:
We have the next directories:
```
.
├── dir
└── text.txt

1 directory, 1 file
```
How we can copy in unix:
`$ cp text.txt dir`
but if we directly rewrite this operation in better-files
`cp(file"text.txt", file"dir")`
it throw `java.nio.file.DirectoryNotEmptyException`, because it try replace `dir` to `text.txt`

For the same operation we should write:
`cp(file"text.txt", file"dir/text.txt") `

I guess, we can fix it in two ways:
1. Change the implementation of `cp` and `mv` to
```scala
def cp(file1: File, file2: File) = {
  val file2FullPath = File(file2.uri.resolve(file1.name)) // add file name to destination name
  file1.copyTo(file2FullPath, overwrite = true)
}
```
but it will break backward compatibility.

2. Highlight this difference in the README documentation

**Comment by pathikrit** [comment] 2018-02-06 15:28
This has been fixed in newer version (duplicate of #182) - fix has been pushed in #183 .

**Closed by pathikrit** 2018-02-06 15:28 UTC
Labels: question
